# Generated by Django 4.2.4 on 2023-09-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
    ]
