# Generated by Django 4.2.4 on 2023-09-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_profile_fb_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
